name: Add Reviewers to pull request
on:
  pull_request:
    branches: master
    
jobs:
  auto-attach-reviewers:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ic3cr3amsandwitch,KulEDmitr
          re-request-when-changes-requested: true
